// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package handler

import (
	"net/http"
	"time"

	userCasdoor "go_zero_pgsql/app/user_center/cmd/api/internal/handler/userCasdoor"
	"go_zero_pgsql/app/user_center/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.I18n},
			[]rest.Route{
				{
					// 用户登录，根据casdoor的code,state换取jwt token
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: userCasdoor.LoginByCasdoorHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/uapi/v1"),
		rest.WithTimeout(3000000*time.Millisecond),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.I18n, serverCtx.CasdoorJwtMiddleware},
			[]rest.Route{
				{
					// 获取用户详细信息
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: userCasdoor.GetUserInfoHandler(serverCtx),
				},
				{
					// 退出
					Method:  http.MethodPost,
					Path:    "/logout",
					Handler: userCasdoor.LogoutHandler(serverCtx),
				},
				{
					// 修改密码
					Method:  http.MethodPost,
					Path:    "/password/update",
					Handler: userCasdoor.UpdateUserPasswordHandler(serverCtx),
				},
				{
					// 登录信息，用于基础时直接获取的用户基础信息
					Method:  http.MethodGet,
					Path:    "/profile/info",
					Handler: userCasdoor.GetUserProfileInfoHandler(serverCtx),
				},
				{
					// 刷新token
					Method:  http.MethodPost,
					Path:    "/token/refresh",
					Handler: userCasdoor.RefreshTokenHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/uapi/v1"),
		rest.WithTimeout(3000000*time.Millisecond),
	)
}
