global:
  scrape_interval:
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  #global catch time
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'user_center-api'
    static_configs:
      - targets: [ 'go_zero_pgsql_api:4001' ]
        labels:
          job: user_center-api
          app: user_center-api
          env: dev
