global:
  scrape_interval: 15s  # 设置全局抓取间隔为15秒
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s  # 保持原有的Prometheus自身监控配置
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'user_center-api'
    static_configs:
      - targets: ['api:4001']
        labels:
          job: user_center-api
          app: user_center-api
          env: dev
