Name: user-api
Host: 0.0.0.0
Port: 8888
Mode: ${GO_ZEOR_MODE}
#Mode: pro test pre dev
#并发请求限制,低于100没用
#MaxConns: 20000
Log:
  ServiceName: user_center_api
  Level: ${GO_ZEOR_LOG_LEVEL}

#监控
Prometheus:
  Host: 0.0.0.0
  Port: 4001
  Path: /metrics
# 有关项目内的配置
ProjectConf:
  #  是否允许初始化
  AllowInit: ${AllowInit}
#Cache:
#  - Host: redis:6379
#    Pass: G62m50oigInCsf
#    Type: node
#短信邮箱服务
McmsRpc:
  Target: localhost:8881
  Enabled: true
  Timeout: 5000

Cache:
  - Host: ${REDIS_BUSINESS_HOST}:${REDIS_BUSINESS_PORT}
    Pass: ${REDIS_BUSINESS_PASSWORD}
    Type: node
Database:
#  postgresql://:mcms_db_pass778@postgres:5432/mcms?sslmode=disable
  PGDataSource: "host=${DB_HOST} port=${DB_PORT} dbname=${USER_DB_NAME} user=${DB_USER} password=${DB_PASSWORD} sslmode=disable"
# 如果需要，可以添加其他配置项
# 例如业务redis,可以和上面的 Cache：
Redis:
  Host: ${REDIS_BUSINESS_HOST}:${REDIS_BUSINESS_PORT}
  Type: node
  Pass: ${REDIS_BUSINESS_PASSWORD}

#链路追踪
Telemetry:
  # 只需要配置服务名字即可,其他不动
  Name: user_center_api
  Endpoint: http://jaeger:14268/api/traces
  Sampler: 1.0
  Batcher: otlpgrpc # grpc
# jwt 登陆传统登录
Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MwEJhl
  AccessExpire: 86400

# 用于密码加密的盐
Salt: HWVOFkGgPTryZICwd7qnJaZR9KQ2i8xe

I18nConf:
  Dir:
ProjectRootPath: ${PROJECT_ROOT}
# Casdoor 单点登陆, 由casdoor服务验证用户登录,退出等, 如果想使用常规登录,注释这一段,开启下面 JwtAuth
CasdoorConfig:
  Endpoint: ${CASDOOR_CONFIG_ENDPOINT}
  ClientId: ${CASDOOR_CONFIG_CLIENT_ID}
  ClientSecret: ${CASDOOR_CONFIG_CLIENT_SECRET}
  OrganizationName: ${CASDOOR_CONFIG_ORGANIZATION_NAME}
  ApplicationName: ${CASDOOR_CONFIG_APPLICATION_NAME}
  # 客户端证书 需要在casdoor 中下载 https://cas.hyue.com/certs 读取文件 这里随便写一个值
#   | 是保留换行符号
  Certificate: |
