// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package types

type GetTokenByCodeReq struct {
	Code  string `json:"code"  label:"code"`
	State string `json:"state"  label:"state"`
}

type GetTokenByCodeResp struct {
	AccessToken  string `json:"access_token"`
	TokenType    string `json:"token_type,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	ExpiresAt    int64  `json:"expires_at,omitempty"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refresh_token"  validate:"required"  label:"refresh_token"`
}

type UpdatePasswordReq struct {
	OldPassword string `json:"oldPassword"  validate:"required,min=6,max=12"  label:"旧密码"`
	NewPassword string `json:"newPassword"  validate:"required,min=6,max=12"  label:"新密码"`
}

type UserInfoResp struct {
	Nickname string `json:"nickname"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type UserProfileInfoResp struct {
	Id       string `json:"id"`
	Nickname string `json:"nickname"`
	Avatar   string `json:"avatar"`
}
