// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1

package types

type GetForgetPasswordCdoeRequest struct {
	Email string `json:"email"     validate:"email"         label:"邮箱"`
}

type JwtAuth struct {
	AccessSecret string `json:"accessSecret"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshToken string `json:"refresh_token,omitempty"`
	ExpiresAt    int64  `json:"expires_at,omitempty"`
}

type LoginRequest struct {
	Email    string `json:"email"     validate:"email"         label:"邮箱"`
	Password string `json:"password"  validate:"required,min=6,max=12"  label:"密码"`
}

type LoginResponse struct {
	JwtAuth
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResponse struct {
	JwtAuth
}

type RegisterRequest struct {
	Email    string `json:"email"     validate:"email"         label:"邮箱"`
	Password string `json:"password"  validate:"required,min=6,max=12"  label:"密码"`
}

type RegisterResponse struct {
	Id    int64  `json:"id"`
	Email string `json:"email"`
}

type ResetPasswordRequest struct {
	Email    string `json:"email"     validate:"email"         label:"邮箱"`
	Password string `json:"password"  validate:"required,min=6,max=12"  label:"密码"`
	Code     string `json:"code"      validate:"required,min=6,max=6"   label:"验证码"`
}

type ResetPasswordResponse struct {
	Success bool `json:"success"`
}

type TestGetUserInfoRequest struct {
	Id   int64 `json:"id" validate:"required,gt=10" label:"用户id"`
	NoId int64 `json:"Noid" validate:"gt=10" label:"非必要用户id"`
}

type UpdatePasswordRequest struct {
	Email       string `json:"email"     validate:"email"         label:"邮箱"`
	OldPassword string `json:"oldPassword"  validate:"required,min=6,max=12"  label:"旧密码"`
	NewPassword string `json:"newPassword"  validate:"required,min=6,max=12"  label:"新密码"`
}

type UserInfoResponse struct {
	Id    int64  `json:"id"`
	Email string `json:"email"`
}
